### ISSUE TITLE
Problem with "Unrecognized function or variable 'mklserv_client'."

### ISSUE THREAD

**Issue by etiennebalmes** [SDTools-support/support#1]
Mklserv_client is a mex file packaging support INTEL PARDISO into the SDT ofact object. It must be installed using

 **sdtcheck('patchMkl')**

**Comment by esaezr** [comment]
Thank you Etienne. I solved the issue, however I had to manually create the "sdtdemos" folder to avoid an error during downloading.

Thank you very much
